# Spring Application Name
spring.application.name=agrotrack-web-service

# Profiles
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# Spring DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.naming.physical-strategy=com.floweytech.agrotrack.iam.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Internationalization (i18n) Configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

# Elements take their values from maven pom.xml build-related information
documentation.application.title=@project.name@
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret=${AUTHORIZATION_JWT_SECRET}
authorization.jwt.expiration.days=${AUTHORIZATION_JWT_EXPIRATION_DAYS}

springdoc.swagger-ui.servers[0].url=https://rentech-iam-service.onrender.com
springdoc.swagger-ui.servers[0].description=Production

# Puerto del servidor (Usa la variable PORT que da Render, o el 8081 en local)
server.port=${PORT:8081}